# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Martin Chapman Fromm
email: martin@chapmanfromm.com
description: > # this means to ignore newlines until "baseurl:"
  Photography by Martin Chapman Fromm.
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.chapmanfromm.com" # the base hostname & protocol for your site
twitter_username: mcf

# Build settings
markdown: kramdown

# Plug-ins
plugins:
  - jekyll-feed
  - jekyll-strapi

# Strapi
strapi:
  # Your API endpoint (optional, default to http://localhost:1337)
  # endpoint: http://localhost:1337
  endpoint: https://strapi-urv0.onrender.com
  collections:
    links:
      type: links
